# docker compose version which is currently 3.8
version: "3.8"

# services : is a list of our container
services:

  backend:
    build: ./server
    ports:
      - "8080:8080"

  frontend:
    build: ./client

    # the port that we want to publish for frontend
    ports:
      - "3000:3000"
    # add bind mount volume to keep have updated source code
    volumes:
      - ./client/src:/app/src
    # allow interactive mode
    stdin_open: true
    tty: true

    # it will start our frontend container once backend-container is  up and running.
    depends_on:
      - backend

# declare the volumes name that our app is using.
volumes:
  data: